# DOCKER COMPOSE
# Allow to start multiple docker containers at the same time specifying configurations for each one and dependencies between them. Also used to start the database

# yml is an easy language, always key value pairs without {}, and with indentation to outline relations
version: '3'
services:
  web:
    build: . # Build file is in the current directory
    ports: 
      - "5001:80"
    volumes: # Copy and keep in sync the current directory with the app directory inside the container
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:

# docker compose up
# docker compose up --build --force--recreate --no-deps service_name (here 'web')